### ISSUE TITLE
Error creating/updating organization #2

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#73] opened 2020-09-08 13:34 UTC
**API-Mgr. CLI version**
1.2.2

**API-Manager and Service-Pack Version**
7.6.2 SP2

I tried again importing organization, modifying the description and then again importing to api manager with the new version 1.2.2.
I got the same error as mentioned in issue #69, I tried to run ImportSimpleOrganizationTestIT on my api Manager and it fails.

This is the final part of the log of integration test.

```
13539  INFO  tionImportTestAction| Copy certificates and images from source: D:\Git\BancoBPM\apim-cli\modules\organizations\target\test-classes\com\a
xway\apim\organization\orgImport into test-dir: 'C:\Users\ADMIN\AppData\Local\Temp\OrgImportActionTest-My-Org-9465-7057'
13542  INFO  tionImportTestAction| Ignoring admin account: 'false' | Enforce breaking change: false | useEnvironmentOnly: false
15361  INFO     APIManagerAdapter| Successfully connected to API-Manager (7.6.2 SP2) on: https://192.168.2.43:8075
16626  ERROR rOrganizationAdapter| Error creating/updating organization. Response-Code: 404. Got response: '{"errors":[{"code":102,"message":"Not Fou
nd"}]}'
16627  ERROR   OrganizationCLIApp| Error creating/updating organization
com.axway.apim.lib.errorHandling.AppException: Error creating/updating organization
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.createOrUpdateOrganization(APIManagerOrganizationAdapter.java:168)
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.updateOrganization(APIManagerOrganizationAdapter.java:112)
        at com.axway.apim.organization.OrganizationImportManager.replicate(OrganizationImportManager.java:33)
        at com.axway.apim.organization.OrganizationCLIApp.importOrganization(OrganizationCLIApp.java:148)
        at com.axway.apim.organization.OrganizationImportTestAction.doExecute(OrganizationImportTestAction.java:107)
        at com.axway.apim.organization.orgImport.ImportSimpleOrganizationTestIT.run(ImportSimpleOrganizationTestIT.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:139)
        at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:110)
        at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:56)
        at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:201)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:642)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at org.testng.TestRunner.privateRun(TestRunner.java:753)
        at org.testng.TestRunner.run(TestRunner.java:607)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
        at org.testng.SuiteRunner.run(SuiteRunner.java:270)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
        at org.testng.TestNG.runSuites(TestNG.java:1124)
        at org.testng.TestNG.run(TestNG.java:1096)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating organization.
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.createOrUpdateOrganization(APIManagerOrganizationAdapter.java:157)
        ... 38 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating organization. Response-Code: 404
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.createOrUpdateOrganization(APIManagerOrganizationAdapter.java:153)
        ... 38 more
16630  INFO       LoggingReporter|
16630  ERROR      LoggingReporter| TEST FAILED ImportSimpleOrganizationTestIT.run <com.axway.apim.organization.orgImport> Nested exception is:
com.consol.citrus.exceptions.ValidationException: Expected RC was: 0 but got: 35
```

**Comment by cwiechmann** [comment] 2020-09-08 18:56
@gcornacchia, firstly I would propose to install the latest service-pack. As you can see it's working fine with a service-pack 7.6.2 SP5:
https://api.travis-ci.org/v3/job/725039517/log.txt

If you would like to get deeper and investigate into the root cause, you might enable debug for the API-Manager REST-API (8075). With that, you see the API-Call triggered by the CLI returning a 404. 
I would be interested into the request details sent to the endpoint. Should be something like:
`/api/portal/v1.3/organizations/<org-id>`
And of course the payload.

**Comment by cwiechmann** [comment] 2020-09-15 11:55
I'm going to close this issue now and the change will be part of the next release. Thanks! @gcornacchia

**Closed by cwiechmann** 2020-09-15 11:55 UTC
Labels: bug
