### ISSUE TITLE
BUILD SUCCESSFUL despite errors during pipeline execution

### ISSUE THREAD

**Issue by MaxNegroni** [Axway-API-Management-Plus/apim-cli#330] opened 2022-11-21 09:52 UTC
### APIM-CLI version

1.12.0

### API-Management version

7.7.20220530

### Question

Hi,

During the execution of the following pipeline there are errors (502 - Bad Gateway most likely due to a network error), but I cannot understand why despite that the result was a SUCCESFUL BUILD: 

```
`"07:49:51 [INFO] New API successfuly created. Going to delete old API: '****' 2.3.1 (ID: ****)  

07:49:53  [ERROR] Error deleting API-Proxy using URI: [https://api-manager-*****](https://api-manager-****). 
Response-Code: 502, Response: '<html>
07:49:53  <head><title>502 Bad Gateway</title></head>
07:49:53  <body>
07:49:53  <center><h1>502 Bad Gateway</h1></center>
07:49:53  </body>
07:49:53  </html>
07:49:53  '
07:49:53  [INFO] Rollback FE-API: '****' (ID: '****' / State: 'unpublished')
07:49:55  [INFO] API: **** v2 2.3.1 (****) successfully deleted
07:49:56  [INFO] Rolled back: '[Frontend-API: false, Backend-API: true]'
07:49:56  [INFO] You may enable debug to get more details. See: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
07:49:56  [ERROR] The status change from: 'deleted' to 'deleted' is not possible!
07:49:56                                   | Cannot delete API-Proxy.
07:49:56                                   | Error deleting API-Proxy. Response-Code: 502
07:49:56  [INFO] ------------------------------------------------------------------------
07:49:56  [INFO] BUILD SUCCESS"`
```

We don't need to understand the reason for the errors, but please we would like to know why the pipeline ends with BUILD SUCCESSFUL despite these errors during execution

Thanks,
Massimo

**Comment by rathnapandi** [comment] 2022-11-21 19:56
The CLI returns status code  for every run, 0 for success and other codes for failures ? how are you invoking the CLI?

**Comment by MaxNegroni** [comment] 2022-11-23 14:35
Yes, correct:
a. 0 stands for success and other codes for failure
b. a Jenkins pipeline is used here

**Comment by rathnapandi** [comment] 2022-11-23 16:17
Can you enable debug log? And share the output?

**Comment by MaxNegroni** [comment] 2022-11-30 14:45
ok so, update, now we are trying to replicate the error and activate DEBUG logs, unfortunatly the person who encountered the error has no DEBUG logs to show

**Comment by zyon1974** [comment] 2022-12-07 15:03
Hello @rathnapandi ,

I think we (me and the team)  misunderstood each other. The issue is not reproducible, we can't replicate the error because it would mean running the pipeline and at the exact same time as last time, we would have to cause a network error.  
From what you can see here, there was a network error in the execution:

07:49:53 [ERROR] Error deleting API-Proxy using URI: [https://api-manager-*****](https://api-manager-****).
Response-Code: **502, Response**: '<html>.
We just wanted to understand why the build doesn't fail even though there are errors:
07:49:56 [INFO] **BUILD SUCCESS**"`

Given the errors mentioned above, the build should not go into a success state.
We would like to ask the following two questions:

**- Is this an expected behavior?**

**- can it be fixed with a subsequent release?**

Best Regards

**Comment by rathnapandi** [comment] 2022-12-07 16:43
Hi @zyon1974 ,

It is not an expected behavior; can you share the apim cli command you ran? It would help to fix the issue.

**Comment by giancolli** [comment] 2022-12-07 17:18
Hi @rathnapandi ,

the operation performed was a Publishing of an already existing API (to update it) via the maven plugin exposed for APIM CLI:

`07:48:55  [INFO] --- publish-axway-maven-plugin:1.0.9:publish (publish-to-axway) @ api-management ---`

Don't mind about version 1.0.9, that's our internal reference to link to APIM CLI v1.12.0.

Thanks

**Comment by rathnapandi** [comment] 2022-12-07 22:00
Hi @giancolli , 

I do see an issue with publish operation. It is not throwing any error for failures. will fix it as part of our next release. 

Ref - PublishAPIHandler.java
[https://github.com/Axway-API-Management-Plus/apim-cli/blob/9847efefd40a8307bfac3df6ffdf70fe83d82153/modules/apis/src/main/java/com/axway/apim/api/export/impl/PublishAPIHandler.java](url)

**Closed** 2022-12-13 21:26 UTC
Labels: bug
