### ISSUE TITLE
no way to export all certificates

### ISSUE THREAD

**Issue by acirami** [Axway-API-Management-Plus/apim-cli#375] opened 2023-03-30 22:32 UTC
### Problem description

we need to export all certificates and when the expire

### Feature request

a way to export all certificates.

**Comment by rathnapandi** [comment] 2023-03-31 01:19
@acirami the certificates are managed as part of APIs. 

For expiry json report refer https://github.com/Axway-API-Management-Plus/apim-cli/issues/374#issuecomment-1491151904

**Comment by rathnapandi** [comment] 2023-04-04 21:51
duplicate of #374

**Closed by rathnapandi** 2023-04-04 21:51 UTC
Labels: enhancement
