### ISSUE TITLE
The output of command 'apim api get' is not containing the complete list of client applications (array) of the api

### ISSUE THREAD

**Issue by martinDevo** [Axway-API-Management-Plus/apim-cli#495] opened 2024-08-29 09:18 UTC
### APIM-CLI version

1.14.5

### API-Management version

7.7.20240530

### Bug description

The output of command 'apim api get' is not containing the complete list of client applications (array) of the api.
Instead, it contains just one application 

### Steps to reproduce

1. Create an API in API Manager and add two clients (apps) with API access, as below in an example
![image](https://github.com/user-attachments/assets/b9dae06a-b72d-43ed-9371-a0e4e261a9c8)

2. Run command ‘apim api get ... -n "Blueprint Service API" -ignoreCache -o yaml -t .\temp’ towards this API Manager (in an EMT topology)

When I do this – with either apim-cli 1.14.4 or 1.14.5 on a Windows11 system with openjdk 17  - then I do *not* get the two client applications in the file output. Instead I always get at most one application (see screenshot, last line).
![image](https://github.com/user-attachments/assets/e351304f-7de6-40cd-8b2d-8b2a9c4dd78c)

**Comment by cbrowet-axway** [comment] 2024-08-29 09:26
I can confirm.

This seems to be a regression as it was working as expected in 1.14.2

**Comment by rathnapandi** [comment] 2024-10-11 19:40
Fixed in 1.14.6

**Closed by rathnapandi** 2024-10-11 19:40 UTC
Labels: bug
