### ISSUE TITLE
Passwords with $ fail authentication in CLI

### ISSUE THREAD

**Issue by jordanwalsh23** [Axway-API-Management-Plus/apim-cli#128] opened 2020-12-10 23:28 UTC
**API-Mgr. CLI version**
1.3.3

**API-Manager and Service-Pack Version**
7.7.20200530

**Expected behavior**
CLI should execute the operation successfully.

**Actual behavior**
CLI fails with a 403 error.

**Log-Output in Debug**
```
1676   ERROR    APIManagerAdapter| Login finally failed with statusCode: 403. Got response: '{"errors":[{"code":403,"message":"Invalid user or password"}]}'
```

**Test case sample**

1. Create a user in api manager
2. Log into api manager with that user - set a new password with a `$`
3. Log out, and confirm you can log back in - password works
4. Authenticate to CLI with the same username/password.
5. Note that the CLI cannot process the request until the `$` is escaped (e.g. `\$`).

**Comment by cwiechmann** [comment] 2021-01-13 22:38
Sorry, for the late response @jordanwalsh23. Today I had the chance to test this, but unfortunately I cannot reproduce the issue on my side. I have created a user with password: `$test123` and it is working fine. No matter if I quote the password or not. I test on a Windows CMD. Both versions are working:
`apim api get -h api-env -u chris -p $test123`
`apim api get -h api-env -u chris -p "$test123"`

I assume it is related to the environment the CLI is executed and based on the $ sign, it tries to evaluate a variable, which obviously fails.

A few questions:
- are you using the apim.sh or apim.bat ?
- on which platform (Windows, Unix, Mac) ?
- which environment (CMD, Powershell, Unix-Shell (Bash, KSH) ?

**Comment by cwiechmann** [comment] 2021-01-28 07:27
Closing this issue for now as invalid. Feel free to re-open @jordanwalsh23

**Closed by cwiechmann** 2021-01-28 07:27 UTC
Labels: invalid
