### ISSUE TITLE
Deletion of authenticationProfile not replicated

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#74] opened 2020-09-08 14:13 UTC
**API-Mgr. CLI version**
> 1.2.1

**API-Manager and Service-Pack Version**
7.7 May20

**Expected behavior**
For an already deployed API with outbound authentication, when I delete an authenticationProfile from the API configuration file and redeploy, I expect apim-cli to detect a change with published API and redeploy the API without any outbound authentication.

**Actual behavior**
Change is not detected. No deployment/update is triggered.

**Log-Output in Debug**
~~~stacktrace
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.1

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.2.1)
----------------------------------------------------------------------------------------
0      DEBUG nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
29     DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
668    WARN  sponseProcessCookies| Invalid cookie header: "Set-Cookie: SSOSPAPIMAN=deleted;Version=1;Comment=;Domain=;Path=/api/portal/v1.3/;Max-Age=0;Secure;HttpOnly". Blank or null value for domain attribute
895    INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200530) on: https://apimanager.net:8075
1007   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=APIMGR Group Core Team, id=null]
1106   DEBUG IImportConfigAdapter| Current path=/mnt/c/GWA/Data/Workspace/Engie/tools/apim-cli-1.2.1
1112   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '../test-api/gwa.json' (relative path)
1120   DEBUG SpecificationFactory| Handle API-Specification: '{
        "swagger": "2.0",
        "info": {
                "description": "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #s......', apiDefinitionFile: '../test-api/gwa.json'
1150   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://apimanager.net:8075/api/portal/v1.3/proxies?field=path&op=eq&value=%2Fgwa%2Ftest%2Fv1
1339   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=beef6ee1-4beb-4185-96e0-141c551da625]
1425   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1672   DEBUG SpecificationFactory| Handle API-Specification: '{
        "swagger": "2.0",
        "info": {
                "description": "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #s......', apiDefinitionFile: 'gwatestapihttps_2020-09-08T14:02:59Z.json'
1785   INFO  APIManagerAPIAdapter| Found existing API on path: '/gwa/test/v1' (published) (ID: 'a90584e6-8507-4482-9a05-6456e6240f77'
1787   DEBUG       APIChangeState| No change for property: apiDefinition[Desired: 'com.axway.apim.api.definition.Swagger2xSpecification@5f16132a' vs Actual: 'com.axway.apim.api.definition.Swagger2xSpecification@69fb6037']
1788   DEBUG       APIChangeState| Ignoring Null-Property: caCerts[Desired: 'null' vs Actual: '[CaCert [name=CN=*.swagger.io, alias=CN=*.swagger.io, md5Fingerprint=81:AD:AF:05:B1:39:ED:FF:BE:EE:79:94:28:B3:F2:10], CaCert [name=CN=Amazon, OU=Server CA 1B, O=Amazon, C=US, alias=CN=Amazon, OU=Server CA 1B, O=Amazon, C=US, md5Fingerprint=EB:26:8E:55:D4:34:FE:BD:A3:6A:97:9A:44:65:4B:6D], CaCert [name=CN=Amazon Root CA 1, O=Amazon, C=US, alias=CN=Amazon Root CA 1, O=Amazon, C=US, md5Fingerprint=E8:65:A2:2A:AE:52:4D:26:86:9A:F0:44:8D:6F:D8:96], CaCert [name=CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US, alias=CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US, md5Fingerprint=C6:15:09:25:CF:EA:59:41:DD:C7:FF:2A:0A:50:66:92]]']
1789   DEBUG       APIChangeState| Ignoring Null-Property: descriptionType[Desired: 'null' vs Actual: 'original']
1790   DEBUG       APIChangeState| No change for property: securityProfiles[Desired: '[SecurityProfile [[SecurityDevice [type=passThrough]]]]' vs Actual: '[SecurityProfile [[SecurityDevice [type=passThrough]]]]']
1791   DEBUG       APIChangeState| Ignoring Null-Property: authenticationProfiles[Desired: 'null' vs Actual: '[AuthenticationProfile [name=_default, isDefault=true, parameters={apiKey=BLABLA, apiKeyField=KeyId, httpLocation=QUERYSTRING_PARAMETER, _id_=0}, type=apiKey]]']
1793   DEBUG       APIChangeState| Ignoring Null-Property: tags[Desired: 'null' vs Actual: '{}']
1794   DEBUG       APIChangeState| Ignoring Null-Property: outboundProfiles[Desired: 'null' vs Actual: '{_default=com.axway.apim.api.model.OutboundProfile@36d585c}']
1795   DEBUG       APIChangeState| Ignoring Null-Property: serviceProfiles[Desired: 'null' vs Actual: '{_default=ServiceProfile [apiId=611fedc6-4265-4f7d-a957-ae38c0fb0229, basePath=https://petstore.swagger.io]}']
1797   DEBUG       APIChangeState| No change for property: inboundProfiles[Desired: '{_default=monitorAPI: true, monitorSubject: ${authentication.subject.id}, securityProfile: _default, corsProfile: _default}' vs Actual: '{_default=monitorAPI: true, monitorSubject: ${authentication.subject.id}, securityProfile: _default, corsProfile: _default}']
1798   DEBUG       APIChangeState| No change for property: corsProfiles[Desired: '[com.axway.apim.api.model.CorsProfile@87a85e1]' vs Actual: '[com.axway.apim.api.model.CorsProfile@671a5887]']
1798   DEBUG       APIChangeState| Ignoring Null-Property: applications[Desired: 'null' vs Actual: '[]']
1799   DEBUG       APIChangeState| No change for property: path[Desired: '/gwa/test/v1' vs Actual: '/gwa/test/v1']
1799   DEBUG       APIChangeState| No change for property: state[Desired: 'published' vs Actual: 'published']
1800   DEBUG       APIChangeState| No change for property: version[Desired: '6.6.6' vs Actual: '6.6.6']
1800   DEBUG       APIChangeState| No change for property: name[Desired: 'GWA Test API' vs Actual: 'GWA Test API']
1801   DEBUG       APIChangeState| No change for property: organization[Desired: ''APIMGR Group Core Team'' vs Actual: ''APIMGR Group Core Team'']
1801   DEBUG       APIChangeState| Ignoring Null-Property: retirementDate[Desired: 'null' vs Actual: '0']
1803   DEBUG     APIImportManager| BUT, no changes detected between Import- and API-Manager-API. Exiting now...
1804   WARN          APIImportApp| No changes detected between Import- and API-Manager-API: 'GWA Test API' (a90584e6-8507-4482-9a05-6456e6240f77)
No changes detected. Existing with RC: 0
~~~

**Test case sample**
> Please describe the steps you have done to replicate the issue
1. Import Sample API "with security-outbound-apikey.json" config file.
2. Remove authenticationProfile from security-outbound-apikey.json file.
3. Reimport same API with updated security-outbound-apikey.json file.
4. Check logs

**Comment by cwiechmann** [comment] 2020-09-08 19:08
@gwandwingor, the behavior you see is expected. I know, this confusing, but there is a reason behind: Efficiency. The CLI is not fetching artifacts/items that are **not set** in the desired state. This avoids to load everything just for nothing. 

I consider this as some kind of edge case happens during development/trying/setup and not when an API is finally deployed into Prod/Pre-Prod. 
Therefore, I recommend to reset the actual state manually with a `forceUpdate`.

**Comment by gwandwingor** [comment] 2020-09-10 14:31
Yes, but one could argue that dev/testing environments are precisely where the apim-cli is used the most.

Anyway, my point is is that the only way to guarantee that what is in the config file is what's going to be published is by using the forceUpdate option. For my customer, this means that this option is going to have to be set by default. (which I have nothing against)
My concern is if other customers also start using it by default, then in terms of efficiency, the outcome might be opposite of what was intended in the first place.

Just my 2 cents here...

**Comment by cwiechmann** [comment] 2020-09-17 05:58
Hmm, you are absolutely right. The problem is, that I don't see a good solution without loading all API-Details from the API-Manager just for nothing. That can be expensive, when it comes to many applications, organizations, quotas, etc.

> Yes, but one could argue that dev/testing environments are precisely where the apim-cli is used the most.

That's why I was thinking: A developer has control and is using the CLI manually controlled. If he is realizing, that the config is not as expected, hence force a re-creation. 
When done, he checks in and from that point, the API-Config can be considered as more stable. And have in mind, this only happens, if someone removes a setting completely.

**Comment by cwiechmann** [comment] 2020-10-05 12:48
I'm going to close this issue as now, as there is nothing I can currently do. Feel free to re-open this issue if you can think of an acceptable solution for this problem.

**Closed by cwiechmann** 2020-10-05 12:48 UTC
Labels: bug
