### ISSUE TITLE
-returnCodeMapping option does not work on apim-cli org import

### ISSUE THREAD

**Issue by jeroenvandermeulen** [Axway-API-Management-Plus/apim-cli#496] opened 2024-09-03 10:24 UTC
### APIM-CLI version

1.14.5

### API-Management version

7.7.20240530

### Bug description

When using the following command:

`apim org import -username $APIMGR_USERNAME -password $APIMGR_PASSWORD -apimanagerUrl $APIMGR_URL -s $CI_COMMIT_BRANCH -c ./${PROJECT_DIR}/client-organizations/Example-client-org-name/org-config.yaml -returnCodeMapping 10:0`

The command does not exit with 0 when the exit code is 10. This while the option to remap this has been specified. This happens for example when there are no changes found with the following warning:

```
2024-09-02 08:44:22,197 [APIManagerCLI] INFO : API-Manager CLI: 1.14.5
[20](redacted/-/jobs/81897#L20)24-09-02 08:44:22,200 [APIManagerCLI] INFO : Module: Organization - E X P O R T / U T I L S  (1.14.5)
2024-09-02 08:44:23,507 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20240530) on: [redacted](redacted)
2024-09-02 08:44:25,964 [OrganizationApp] INFO : You may enable debug to get more details. See: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
2024-09-02 08:44:25,965 [OrganizationApp] WARN : No changes detected between Desired- and Actual-Org: Example client org name.
```

We get `ERROR: Job failed: command terminated with exit code 10` in our CI and can also validate the same behaviour locally when running `echo $?`

The -returnCodeMapping option does seem to work when using it in for example `apim api import`

### Steps to reproduce

`apim org import -username $APIMGR_USERNAME -password $APIMGR_PASSWORD -apimanagerUrl $APIMGR_URL -s $CI_COMMIT_BRANCH -c ./${PROJECT_DIR}/client-organizations/Example-client-org-name/org-config.yaml -returnCodeMapping 10:0`

### Relevant log output

```shell
2024-09-02 08:44:22,197 [APIManagerCLI] INFO : API-Manager CLI: 1.14.5
[20](redacted/-/jobs/81897#L20)24-09-02 08:44:22,200 [APIManagerCLI] INFO : Module: Organization - E X P O R T / U T I L S  (1.14.5)
2024-09-02 08:44:23,507 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20240530) on: [redacted](redacted)
2024-09-02 08:44:25,964 [OrganizationApp] INFO : You may enable debug to get more details. See: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
2024-09-02 08:44:25,965 [OrganizationApp] WARN : No changes detected between Desired- and Actual-Org: Example client org name.
```
```

**Comment by cbrowet-axway** [comment] 2024-09-06 12:35
I confirm the issue.
From a quick look at the code, it seems `returnCodeMapping` is not implemented for Organizations

**Comment by rathnapandi** [comment] 2024-10-11 19:41
Fixed in 1.14.6

**Comment by martinDevo** [comment] 2024-10-30 12:52
It looks to me as if the issue hasn't been resolved.

My apim-cli command example (doing an org import) and the apim-cli response:
![image](https://github.com/user-attachments/assets/63141f07-8f3e-42b0-8faa-40408d546bed)

Here the status code after the command execution (expecting status code=0 by the -returnCodeMapping option)
![image](https://github.com/user-attachments/assets/47b5c6f1-9add-4307-a0fe-63124099004e)

Using apim-cli version 1.14.6
![image](https://github.com/user-attachments/assets/86233997-c97f-4c67-813f-cbb3de89f8b7)

Please can you re-investigate the issue.
Thank you.

**Comment by martinDevo** [comment] 2024-10-30 12:57
@cbrowet-axway @jeroenvandermeulen , could you also check whether you find if the issue is resolved ? Thanks.

**Comment by martinDevo** [comment] 2024-10-31 10:03
Hello Rathna,

Thanks for quick reply!
Your latest changes (in 1.14.8-SNAPSHOT) are providing the expected results, afaict :-)

Importing an already existing organization:
![image](https://github.com/user-attachments/assets/d850e847-6595-4276-8df3-b23cdd70cfc1)
return code  = 10 (no changes detected)
![image](https://github.com/user-attachments/assets/ca4d6100-1130-4118-9f6f-9acff9fa8562)
Then with the returnCodeMapping 10:0 added
![image](https://github.com/user-attachments/assets/cc5dbf7a-40de-48a0-a4ee-862c83b0ae27)
return code = 0 (the mapping did its job)
![image](https://github.com/user-attachments/assets/8e4cd897-1f64-4028-8735-7757e197fd9c)

Great, thanks,
Martin.

**Closed** 2024-11-06 17:05 UTC
Labels: bug
