### ISSUE TITLE
cache for organizations

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#463] opened 2024-03-08 22:19 UTC
### APIM-CLI version

1.14.2

### API-Management version

7.7.20231130

### Question

Every time I execute apim api get it is showing this line:
2024-03-08 19:06:01,889 [APIManagerOrganizationAdapter] DEBUG: Organization id to be cached : /657a7bea-0778-XXX-XXXX-XXXXXX

I wonder it the cache is not being persisted in my installation .. I would expect this run on the first iteration, and then it gets it from the cache 
I am testing this with the command-line (not from a java project). 

Thanks

**Comment by rathnapandi** [comment] 2024-03-11 19:12
@emmanuel-galindo 
Can you use the flag -enabledCaches organizationCache for api import. please refer https://github.com/Axway-API-Management-Plus/apim-cli/wiki/8.4.-Caching for information.

**Comment by emmanuel-galindo** [comment] 2024-03-11 21:49
Thanks @rathnapandi .. I've tried it, but it keeps hitting APIM /organizations endpoint once and again.
also, it prints this at beggining:
2024-03-11 18:48:29,937 [APIMCLICacheManager] ERROR: The cache: organizationCache is currently not supported for import actions.

**Comment by rathnapandi** [comment] 2024-03-12 04:04
Hi @emmanuel-galindo, 

Can you share the command line parameters which you used for testing?

**Comment by emmanuel-galindo** [comment] 2024-03-12 15:07
Hi, sorry I just noticed that my initial report was around "apim api get", not import.

That's where I see that line. I think "apim api get" comes with all caches by default right? I ran it anyways with  -enabledCaches organizationCache but same result. 

I am looking to improve speed of "apim api get" when searching for id

**Comment by rathnapandi** [comment] 2024-10-17 00:27
Hi @emmanuel-galindo, 
api get and import operations are optimized, can you please test it with https://github.com/user-attachments/files/17404429/axway-apimcli-1.14.7-SNAPSHOT.tar.gz and let me know the outcome.

**Comment by rathnapandi** [comment] 2024-10-17 18:03
Duplicate of #500

**Closed by rathnapandi** 2024-10-17 18:03 UTC
Labels: question
