### ISSUE TITLE
Incorrect exit RC being returned from the apim script ?

### ISSUE THREAD

**Issue by kunwardhwaj** [Axway-API-Management-Plus/apim-cli#33] opened 2020-06-29 17:04 UTC
**API-Mgr. CLI version**
1.1.0

**API-Manager and Service-Pack Version**

7.6.2/SP3
**Expected behavior**
In case there is an exception, return code from the script should be not equal =0

**Actual behavior**
If we are passing incorrect password to the script, we are getting an exception. Still the RC returned from the script =0. 
Because of this , Jenkins pipeline job is always successful even though it caught an exception.

Can you please confirm if this is an issue or is this how it was intended to behave ?

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

Passed incorrect API Manager password to the script. See below stack trace outout:
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.1.0

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.1.0)
----------------------------------------------------------------------------------------
0      WARN     APIManagerAdapter| Login failed with statusCode: 403. Got response: '{"errors":[{"code":403,"message":"Invalid user or password"}]}' ... Try again in 1 second.
1491   ERROR    APIManagerAdapter| Login finally failed with statusCode: 403. Got response: '{"errors":[{"code":403,"message":"Invalid user or password"}]}' Got response: '{"errors":[{"code":403,"message":"Invalid user or password"}]}'
1496   ERROR         APIImportApp| Can't login to API-Manager
com.axway.apim.lib.errorHandling.AppException: Can't login to API-Manager
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:231)
        at com.axway.apim.adapter.APIManagerAdapter.<init>(APIManagerAdapter.java:172)
        at com.axway.apim.adapter.APIManagerAdapter.getInstance(APIManagerAdapter.java:133)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:138)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:76)
Caused by: com.axway.apim.lib.errorHandling.AppException: Login finally failed with statusCode: 403
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:213)
        ... 9 more
```

**Comment by cwiechmann** [comment] 2020-06-30 05:31
@kunwardhwaj, thanks for reporting this. Of course this is not the intended behavior and will be fixed in the next version.

**Comment by cwiechmann** [comment] 2020-06-30 06:15
@kunwardhwaj, The issue is fixed and was basically an error in the CLI-Wrapper calling the module. The CLI-Wrapper hasn't taken over the returned error-code from the called module, such as API-Import. 

If you want you can fix your pipeline now by calling the API-Import directly without using the CLI-Wrapper. The CLI wrapper is only required to provide that convenience menu to discovery available modules. 

I assume you are using a JAVA-Call in your pipeline, which is currently configured like so:
`com.axway.apim.cli.APIManagerCLI apim api import -c ......`

Instead you can also call the import module directly:
`com.axway.apim.APIImportApp -c ....`

As you are using the pipeline integration, I guess you know about the Return-Code Mapping feature: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/7.-Pipeline-integration#return-code-mapping 
Which might be quite helpful in some situations.

**Comment by cwiechmann** [comment] 2020-06-30 06:33
Fixed

**Closed by cwiechmann** 2020-06-30 06:33 UTC
Labels: bug
