### ISSUE TITLE
Problem exporting API to json

### ISSUE THREAD

**Issue by tiagomistral** [Axway-API-Management-Plus/apim-cli#98] opened 2020-10-21 14:18 UTC
**API-Mgr. CLI version**
apim-cli-1.2.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
Export the given API and create the json-files and certs

**Actual behavior**
Despite the tool throwing an error, the export folder gets created, but the api-definition, as well as the api-config is incomplete (e.g. missing apps and orgs and closing curly brackets). Also no certs are created.

**Log-Output in Debug**
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.3

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.2.3)
----------------------------------------------------------------------------------------
1704   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://localhost:8075
13766  INFO          APIExportApp| 1 API(s) selected.
13769  INFO       JsonAPIExporter| Going to export API into folder: .\myapi-v4
13938  ERROR      JsonAPIExporter| Can't export API: Can't create API-Configuration file for API: 'MyAPI V4' exposed on path: '/myapi/v4'. Please check in API-Manager UI the API is valid.
com.axway.apim.lib.errorHandling.AppException: Can't create API-Configuration file for API: 'MyAPI V4' exposed on path: '/myapi/v4'.
        at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:116)
        at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:52)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:154)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:67)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.axway.apim.api.export.ExportAPI["customProperties"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3160)
        at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:114)
        ... 10 more
Caused by: java.lang.NullPointerException
        at com.axway.apim.api.export.ExportAPI.getCustomProperties(ExportAPI.java:212)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
        ... 16 more`

**Test case sample**
Use this configuration to import a sample API:
```
{
  "name" : "My API API",
  "path" : "/myapi/v4",
  "state" : "published",
  "version" : "1.0.0",
  "organization" : "organization",
  "apiDefinition" : "sampleAPI.yaml",
  "summary" : "API summary.",
  "backendBasepath" : "sample-basepath",
  "tags":{
   "tag-name 2":[
      "value 3",
      "value 4"
   ],
   "tag-name 1":[
      "value 1",
      "value 2"
   ]
  }
}
```
Test case sample: apim api get -a /myapi/v4 -o json

** Comments **
I also tried to export the API with Swagger Promote 1.6.7-1 and it works fine.

**Comment by prernatiwa** [comment] 2020-10-22 04:57
I am experiencing the same issue.

$ scripts/apim.sh api get -s api-env -n "OpenWeather-API-2.0" -o json 
/usr/bin/java

----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.3
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.2.3)
----------------------------------------------------------------------------------------
709    INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200930) on: https://13.238.236.77:8075
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.ehcache.sizeof.ObjectGraphWalker (file:/Users/prernatiwari/Downloads/apim-cli-1.2.3/lib/ehcache-3.8.1.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.ehcache.sizeof.ObjectGraphWalker
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1906   INFO          APIExportApp| 1 API(s) selected.
1908   INFO       JsonAPIExporter| Going to export API into folder: ./api-v1
1937   ERROR      JsonAPIExporter| Can't export API: Can't create API-Configuration file for API: 'OpenWeather-API-2.0' exposed on path: '/api/v1'. Please check in API-Manager UI the API is valid.
com.axway.apim.lib.errorHandling.AppException: Can't create API-Configuration file for API: 'OpenWeather-API-2.0' exposed on path: '/api/v1'.
	at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:116)
	at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:52)
	at com.axway.apim.APIExportApp.execute(APIExportApp.java:154)
	at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:67)
	at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.axway.apim.api.export.ExportAPI["customProperties"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3160)
	at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:114)
	... 10 more
Caused by: java.lang.NullPointerException
	at com.axway.apim.api.export.ExportAPI.getCustomProperties(ExportAPI.java:212)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 16 more

**Comment by cwiechmann** [comment] 2020-10-22 05:02
Thanks for reporting. The issue is already fixed in the source and will be delivered with the next version.
Plan is to deliver the next release mir of November. Is this sufficient?

**Comment by tiagomistral** [comment] 2020-10-23 12:59
@cwiechmann that's sufficient :)

**Comment by cwiechmann** [comment] 2020-10-26 15:10
Closing this issue now, as it is fixed and will be delivered with the next release.

**Closed by cwiechmann** 2020-10-26 15:10 UTC
Labels: bug
